obj-$(CONFIG_MS_EMMC) += emmc/
obj-$(CONFIG_MS_SDMMC) += sdmmc/
obj-$(CONFIG_MS_NAND) += unfd/
obj-$(CONFIG_MS_ISP_FLASH) += flash_isp/
obj-$(CONFIG_MS_AESDMA) += aesdma/
obj-$(CONFIG_MS_SPINAND) += spinand/
#obj-$(CONFIG_MS_USB) += usb/usbdcore.o usb/usbtty.o usb/ehci_usb.o
obj-$(CONFIG_MS_USB) += usb20/drvhostlib.o usb20/ubootglue.o
obj-$(CONFIG_MS_ENABLE_USB_LAN_MODULE) += usb20/usb_lan.o usb20/ax88772a.o usb20/rtl8150.o usb20/pegasus.o
#obj-$(CONFIG_ENABLE_FIRST_EHC) +=  usb/drvusbmain.o usb/drvhostlib.o
#obj-$(CONFIG_ENABLE_SECOND_EHC) += usb/drvusbmain2.o usb/drvhostlib2.o
#obj-$(CONFIG_ENABLE_THIRD_EHC)	 +=	usb/drvusbmain3.o usb/drvhostlib3.o

#obj-$(CONFIG_MS_ENABLE_USB_LAN_MODULE) += usb/usb_lan.o usb/ax88772a.o

obj-$(CONFIG_MS_EMAC) += emac/
obj-$(CONFIG_MS_NOE) += noe/
obj-$(CONFIG_MS_GPIO) += gpio/
obj-$(CONFIG_MS_PARTITION) += partition/
obj-$(CONFIG_MS_SRCFG) += isp/
obj-$(CONFIG_SYS_I2C_MSTAR) += i2c/
obj-$(CONFIG_HW_WATCHDOG) += wdt/
obj-$(CONFIG_MS_PWM) += pwm/
obj-$(CONFIG_MS_DISP) += disp/
obj-$(CONFIG_MS_SATA_HOST) += sata/
